version: "3.9"

services:
  db:
    image: postgres:15
    container_name: todos_db
    restart: always
    environment:
      POSTGRES_USER: manager
      POSTGRES_PASSWORD: manager
      POSTGRES_DB: task
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: todos_app
    depends_on:
      - db
    environment:
      - PYTHONPATH=/
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=manager
      - DB_PASSWORD=manager
      - DB_DATABASE=task
      - DB_SECRET_KEY=5EPR0T0N3C24
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=5
      - JWT_SECRET_KEY=PR0T0N3C24
      - DEFAULT_LIMIT=100
      - MAX_LIMIT=500
      - PROJECT_NAME=App Task
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge

